name: GitHub Actions Demo
on: [push]
jobs:
  Launch-ClearML-Task:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Testing if the repository will run remotely without issues."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: Install clearml so we can send the repository
        run: |
          pip install clearml
      - name: Run ClearML Task to package the main entrypoint of the repository
        run: |
          clearml-task --project github_actions --name test_${{ github.repository }} --repo ${{ github.repositoryUrl }} --branch ${{ github.ref }} --script main.py --queue default
      - run: echo "This job's status is ${{ job.status }}."